### ISSUE TITLE
My own version of testcontainers-dotnet

### ISSUE THREAD

**Issue by isen-ng** [docker-archive-public/testcontainers.testcontainers-dotnet-legacy#40]
Hello,

Not sure if you guys are interested, I've written my own version testcontainers-dotnet and it supports lots of stuff like:

* ryuk
* exposed ports (with auto publish)
* port binding
* bind mount, 
* Microsoft Enterprise Logging,
* Microsoft Dependency Injection, 
* etc

Most of the code is inspired from this repository and the testcontainers-java repository.

And here it is:
https://github.com/isen-ng/testcontainers-dotnet

**Comment by farodin91** [comment]
This sounds great.

**Comment by swissarmykirpan** [comment]
Hey @isen-ng thanks for this, @HofmeisterAn and I have already spoken about bringing a lot of what he has done in his flavour across to the version that currently exists, and it would be awesome to get your ideas on board as well :)

**Comment by HofmeisterAn** [comment]
It would be great if you join us on [Slack](http://testcontainers.slack.com) and we discuss how to continue. This is my implementation: https://github.com/HofmeisterAn/dotnet-testcontainers.

**Comment by isen-ng** [comment]
I would like to join your Slack workspace, but I think I need an invite first.
My email address is `isengrim613@gmail.com`

It would be an honor to contribute to test containers. I've used java version in the past to run all of my integration tests, and now am working on dotnet. I'm currently using my own version at my work place, so I'm actively maintaining it.

**Comment by HofmeisterAn** [comment]
I sent you an invitation. It's the same for me. However, I have put my focus on a .NET specific implementation. I've tried to create a simple and clean implementation of Testcontainers.

I think we should collect the existing functions. Then we can work out the differences to Testcontainers in Java and implement new functions.
