### ISSUE TITLE
Update test and code coverage results

### ISSUE THREAD

**Issue by HofmeisterAn** [docker-archive-public/testcontainers.testcontainers-dotnet-legacy#50]
File are located in `./test-results` and `./test-coverage`.

- [ ] Update test and code coverage results (develop, or and master).

**Comment by HofmeisterAn** [comment]
@swissarmykirpan @isen-ng I think we should create the coverage statistics for each branch (`bugfix/*`, `feature/*`, develop and master). With the coverage information in PRs, we have an additional check, if we like.

Should we publish the test results as well? What about static code analysis? Sonarcloud would provide all of these features, should we switch? What do you think?

**Comment by isen-ng** [comment]
> I think we should create the coverage statistics for each branch (bugfix/*, feature/*, develop and master)

I don't think we should do the tests for every branch. Only pushes to `develop` and `master` branches and PRs only. Testing on bugs and feature branches is a waste of resources IMO because there may be many irrelevant pushes before the actual PR. And since we are going to fork, there shouldn't be any bug & feature branches to test as well.

> Should we publish the test results as well?

Yes I think so. let's select a service to use and upload our reports. I used `codecov.io` in my code. There should also be a check in PRs (although the check may not be required to pass right now).

> What about static code analysis? Sonarcloud would provide all of these features, should we switch? 

I like sonarcloud as well but I just could not get PR analysis and PR checks to work properly... sigh.

**Comment by swissarmykirpan** [comment]
> @swissarmykirpan @isen-ng I think we should create the coverage statistics for each branch (`bugfix/*`, `feature/*`, develop and master). With the coverage information in PRs, we have an additional check, if we like. 

I think it makes sense running tests only for PRs

> Should we publish the test results as well? What about static code analysis? Sonarcloud would provide all of these features, should we switch? What do you think?

I've used Sonarcloud in the past and it's good.

**Comment by swissarmykirpan** [comment]
If we want this to beneficial, we need to allow for whatever rules and test coverage statistics to be available on the developers local machine, without having to run create a PR. 

Test Execution works out of the box, but things like code coverage will need some thought

**Comment by HofmeisterAn** [comment]
> but things like code coverage will need some thought

If we build each branch, we would at least see the results in Sonarcloud. I have no idea how we can cover everything local.

**Comment by swissarmykirpan** [comment]
> > but things like code coverage will need some thought
> 
> If we build each branch, we would at least see the results in Sonarcloud. I have no idea how we can cover everything local.

https://www.sonarlint.org/visualstudio/

**Comment by HofmeisterAn** [comment]
> > > but things like code coverage will need some thought
> > 
> > 
> > If we build each branch, we would at least see the results in Sonarcloud. I have no idea how we can cover everything local.
> 
> https://www.sonarlint.org/visualstudio/

😂 I totally forgot about SonarLint. I didn't know it supported VSC, great!

**Comment by isen-ng** [comment]
I've used self hosted sonarqube in the past.
The server isn't doing any analysis but compare results with the quality gate.
All the analysis is done locally.

Not sure if we could do that on sonarcloud

**Comment by isen-ng** [comment]
for code coverage, rider 2019 comes shipped with it out of the box.
I bet it's using `dotcover` tool, integrates with coverlet as well.

https://medium.com/@DomBurf/performing-code-coverage-for-net-core-2-0-applications-7280dd2af22b

**Comment by swissarmykirpan** [comment]
we should just be able to use sonarcloud for it all :)

**Comment by HofmeisterAn** [comment]
I have the Cake tasks already prepared after we merged the PR #52, I can add the SonarCloud support.

**Comment by HofmeisterAn** [comment]
@swissarmykirpan If you create a SonarCloud account and add following environment variables to AppVeyor `SONARQUBE_URL`, `SONARQUBE_KEY`, `SONARQUBE_ORGANIZATION` and `SONARQUBE_TOKEN`, I can create the PR to close this issue. SonarCloud will show you the values as soon as you create a project. If you need help to map the values to the environment variables, let me know.

I highly recommend secure variables for API keys.
