### ISSUE TITLE
Repository seems to have gone stale. Objections to taking it over?

### ISSUE THREAD

**Issue by ewassef** [docker-archive-public/testcontainers.testcontainers-dotnet-legacy#91]
This repository hasn't moved much in almost a year but there is still a huge need for this. I do not mind taking it over here or forking it and maintaining it externally. However, I believe it makes sense to keep it under this main organization.

Are the plans for keeping this up and maintaining it or is it dead?

@rnorth  @TheConstructor  @moreirayokoyama  @bsideup  @farodin91

**Comment by hauntingEcho** [comment]
It seems like the primary fork of this is at https://github.com/HofmeisterAn/dotnet-testcontainers - if this project is abandoned, it may make sense to archive the repository and point newcomers in that direction (or merge it back here for continued development, depending on how @HofmeisterAn / the TestContainers team want to handle things).

**Comment by rnorth** [comment]
We'll arrange some discussions to try and clarify things - it'd be nice if we could pull this all back together. Sorry for the slow response, but it is something we're aware of and want to resolve.

**Comment by FlorianHockmann** [comment]
Any news on this? The last commit on `master` was nearly a year ago and the version from @HofmeisterAn is now much more popular than the official version with ~25x as many daily downloads (485 vs 19).
I think the best option for users by now would be to simply make the version from @HofmeisterAn the official one (ideally by moving it into the testcontainers org if @HofmeisterAn agrees to that) and then continue from there as @hauntingEcho also already suggested. That would allow most .NET users of Testcontainers an easy migration to the official library.

**Comment by HofmeisterAn** [comment]
Some years ago, there were efforts to put all three Testcontainers (.NET) implementations together. Unfortunately, without success. I think today there are even more and similar implementations out there.

Back then, we tried to move the structure from @isen-ng implementation to the official repository. @isen-ng did a great job. As far as I know, his implementation is pretty close to the Java implementation. I offered to take care of the pipeline and the missing WCOW implementation. However, the (proposal) structure never got merged.

I can only [repeat](https://github.com/HofmeisterAn/dotnet-testcontainers/discussions/442#discussioncomment-2535311) myself, that there are so many benefits and synergies bundling all the work together. As I said and offered a few times, I'm happy to share my knowledge and work. If there's anything I can do, I'm happy to jump in.

**Comment by bsideup** [comment]
Hey @HofmeisterAn! I really think we should restart the conversation and consider making your version "official" 👍 Let's discuss in Slack, but I see no reasons why not - you are doing a great job and this repo indeed haven't received any love for many months.

**Comment by HofmeisterAn** [comment]
@bsideup I'm on vacation until the end of the month. I'll get back to you afterwards.

**Comment by isen-ng** [comment]
Thank you for your kind words, @HofmeisterAn.
However, a nicely implemented version will not be as useful as a version that is in use by many people. Your version is a lot of more thoroughly tested by users, and since it's a lot more popular, I think your API designs resonate a lot more with .NET developers.

I also think we should use your version as the official version. I would be glad to help out in any way. CI, tests, documentation, etc. I'm all good. (I'll probably help to pick up issues with `help needed` tags)

**Comment by HofmeisterAn** [comment]
FYI: We transferred the repository. There are a few [small](https://github.com/testcontainers/testcontainers-dotnet/issues/476) things we need to take care of, but nothing major 🎉.
